CREATE SEQUENCE IF NOT EXISTS comments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS posts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE comments
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content TEXT                                     NOT NULL,
    user_id BIGINT                                   NOT NULL,
    post_id BIGINT                                   NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(50)                              NOT NULL,
    content TEXT                                     NOT NULL,
    user_id BIGINT                                   NOT NULL,
    CONSTRAINT posts_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                             NOT NULL,
    email VARCHAR(100)                             NOT NULL,
    role  VARCHAR(50)                              NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE comments
    ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE NO ACTION;

ALTER TABLE comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE posts
    ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;