CREATE SEQUENCE IF NOT EXISTS comments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS posts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                             NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    role  VARCHAR(50)                              NOT NULL,
    password varchar(255) not null default '12345',
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS posts
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(50)                              NOT NULL,
    content TEXT                                     NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT posts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content TEXT                                     NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);
