ALTER TABLE comments
ALTER
COLUMN content TYPE VARCHAR(255) USING (content::VARCHAR(255));

ALTER TABLE posts
ALTER
COLUMN content TYPE VARCHAR(255) USING (content::VARCHAR(255));

ALTER TABLE users
ALTER
COLUMN email TYPE VARCHAR(255) USING (email::VARCHAR(255));

ALTER TABLE users
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE comments
DROP
COLUMN post_id;

ALTER TABLE comments
DROP
COLUMN user_id;

ALTER TABLE comments
    ADD post_id INTEGER NOT NULL;

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE users
ALTER
COLUMN role TYPE VARCHAR(255) USING (role::VARCHAR(255));

ALTER TABLE posts
ALTER
COLUMN title TYPE VARCHAR(255) USING (title::VARCHAR(255));

ALTER TABLE comments
    ADD user_id INTEGER NOT NULL;

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE posts
DROP
COLUMN user_id;

ALTER TABLE posts
    ADD user_id INTEGER NOT NULL;

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);